version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: kubrc_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    build: .
    container_name: kubrc_receipt
    restart: always
    environment:
      MONGO_URI: "mongodb://mongodb:27017"
    depends_on:
      - mongodb
    ports:
      - "5000:5000"

volumes:
  mongodb_data:
