apiVersion: v1
kind: Pod
metadata:
  name: mongodb
spec:
  containers:
    - name: mongodb
      image: mongo:latest
      args: ["--noauth"]
      ports:
        - containerPort: 27017
      volumeMounts:
        - mountPath: /data/db
          name: mongodbdata
  volumes:
    - name: mongodbdata
      hostPath:
        path: ./data
        type: DirectoryOrCreate
